name: 'Deploy Web to GitHub Pages'
description: 'Deploy Flutter web app to GitHub Pages'

inputs:
  artifact_name:
    description: 'Name of the artifact to deploy'
    required: true
  github_token:
    description: 'GitHub token for deployment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download Web Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ./web-build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ./web-build
        publish_branch: gh-pages
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy staging web app to GitHub Pages'
